// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  header: dynamic(() => import("./Header")),
  header_slice: dynamic(() => import("./TitleSlice")),
  preview_slice: dynamic(() => import("./PreviewSlice")),
};
